### ISSUE TITLE
Source?

### ISSUE THREAD

**Issue by nasyrov** [Gibbs/uk-postcodes#14]
Hi @Gibbs,

Thanks for the repo, would you mind to share the source of the data? How fresh is the data?

Thanks,
Evgenii

**Comment by Gibbs** [comment]
I honestly can't remember. It was a free data set available around 12 years ago but has changed considerably over that time. I put it on Github in 2012 so people could fork it. 

There are more reliable sources such as the Ordnance Survey https://www.ordnancesurvey.co.uk/opendatadownload/products.html
