### ISSUE TITLE
Letchworth Garden City missing?

### ISSUE THREAD

**Issue by IanGrainger** [Gibbs/uk-postcodes#17]
Hi, thanks for the dataset - unfortunately it doesn't seem to contain Letchworth Garden City  https://en.wikipedia.org/wiki/Letchworth - which was founded in 1903.

I'm afraid I can't trust whatever the source of this is if it doesn't contain towns created over a century ago! :')

**Comment by Gibbs** [comment]
Towns are NOT accurate. IIRC that used to be in the readme but must have got lost somewhere. The dataset is for **out codes** which often covers multiple towns. For example SG6 is currently resolving to Hitchin.

If you are looking for more accurate towns you will need to use a full data set which with Ordnance Survey provides. https://www.ordnancesurvey.co.uk/opendatadownload/products.html

**Comment by IanGrainger** [comment]
Ah, OK - thanks for the clarification :)
