### ISSUE TITLE
This data is available free

### ISSUE THREAD

**Issue by IanGrainger** [Gibbs/uk-postcodes#18]
This data is available free here: https://www.ordnancesurvey.co.uk/business-and-government/products/os-open-names.html.

Please add to readme!

**Comment by Gibbs** [comment]
This is a different data set (out codes) but I'll get something added

**Comment by IanGrainger** [comment]
Sorry, what do you mean about out codes? It has full post codes - example copy+paste from what I happened to have open in SSMS:

```
ID	NAMES_URI	NAME1	NAME1_LANG	NAME2	NAME2_LANG	TYPE	LOCAL_TYPE	GEOMETRY_X	GEOMETRY_Y
ZE10WJ	http://data.ordnancesurvey.co.uk/id/postcodeunit/ZE10WJ	ZE1 0WJ	NULL	NULL	NULL	other	Postcode	445727.000	1139858.000
ZE10TX	http://data.ordnancesurvey.co.uk/id/postcodeunit/ZE10TX	ZE1 0TX	NULL	NULL	NULL	other	Postcode	440255.000	1139597.000
ZE29HY	http://data.ordnancesurvey.co.uk/id/postcodeunit/ZE29HY	ZE2 9HY	NULL	NULL	NULL	other	Postcode	440461.000	1123357.000
```

**Comment by Gibbs** [comment]
Sorry I meant the data in *this* repository is outcodes only. E.g. ZE1 not ZE1 0WJ, ZE1 0TX etc

**Comment by IanGrainger** [comment]
Cool - so this repo is still totally useful when you need the postcode outcode areas.

Is possible to compute from this dataset - but I won't be doing that!

Thanks for providing this repo. :)
