### ISSUE TITLE
UK postcode converter?

### ISSUE THREAD

**Issue by glickja** [Gibbs/UK-Postcodes#7]
Hi,
I was wondering if the code converts postcodes to towns?

I' hope this isn't too silly a question - I'm new to this!

Best wishes,

Joe Glick

**Comment by laczoka** [comment]
"I was wondering if the code converts postcodes to towns?" 

could you elaborate on what exactly do you want to achieve?

This postcode dataset already maps outward postcodes (i.e. the first few letters of a valid UK postcode) to towns, well mostly.

**Comment by glickja** [comment]
I want my wordpress website to convert UK postcodes and US zipcodes to towns and cities.

Thank you for replying!

**Comment by ashfinlayson** [comment]
Look at the data, you've got city name/town/village etc for each row. so
any matching postcode or partial postcode can be mapped to a town name

**Comment by laczoka** [comment]
e.g. M13 9PL is a postcode in Manchester. You can look it up by taking the outward part (M13) and doing an SQL lookup:

SELECT town FROM outcodes WHERE postcode = 'M13'

Will return Manchester.

**Comment by Gibbs** [comment]
@glickja This repository simply contains data. You will be required to develop whatever tool you need for Wordpress.
