### ISSUE TITLE
Second Part of Postcode

### ISSUE THREAD

**Issue by JamesSimpson** [Gibbs/UK-Postcodes#8]
Wouldn't it be worth adding the second parts of the Postcodes to the list, along with Street Names?

**Comment by Gibbs** [comment]
Yes it would but it would be harder to maintain. Street names are also copyright Royal Mail PAF (IIRC).

**Comment by JamesSimpson** [comment]
The second parts of the postcodes shouldnt be too hard to maintain, but agree that the street names could start to get a little messy, but could contain them all.

Street Names are copyright!? Never? - I'll do a little research into this, just wonder how those companies that sell the databases get away with it.

**Comment by Gibbs** [comment]
Copyright might not be correct but the PAF is (and can't be used). If you want full postcodes you might be interested in Code-Point Open https://www.ordnancesurvey.co.uk/business-and-government/products/code-point-open.html

**Comment by JamesSimpson** [comment]
Yea I was just reading up on PAF - http://www.poweredbypaf.com/licensing-centre/public/

Seems a little... strange, but ok.

**Comment by JamesSimpson** [comment]
The reason I was thinking the second parts of post codes, is some post codes I.E. DN15 covers a few different regions. I know it would make the database huge, but it may be worth it with a few more contributors.
